### ISSUE TITLE
[Bug]: `TextField` `endIcon` prop does not support `IconButton`

### ISSUE THREAD

**Issue by p44dyoachim** [project44/manifest#412]
### Description

A common pattern for input fields is to include a "clear text" icon at the end of the field. `TextField` allows the button into the prop, but cannot be clicked. The sizing is off as well even when using smaller `IconButton` sizes. I'm unsure if `TextArea` has similar issues

![Screenshot 2023-06-22 at 8 50 53 AM](https://github.com/project44/manifest/assets/101657561/4a98c8dd-a9e3-4c1a-a965-86df56bd5084)

### Link to reproduction

https://project44.github.io/manifest/inputs/text-field

### Steps to reproduce

Add `IconButton` to `TextField endIcon` and try to click the icon.
```
<TextField
  onChange={setValue}
  value={value}
  endIcon={
    <IconButton
      onPress={() => console.log('was clicked');}
      children={<Icons.Close />}
    />
  }
/>
```

### Code of Conduct

- [X] I agree to the [Code of Conduct](https://github.com/project44/manifest/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] I have reviewed the [current issues](https://github.com/project44/manifest/issues) for duplicate tickets.

**Comment by vivek-p44** [comment]
@p44dyoachim This is happening due to css we are adding to endIcon in TextFieldBase component, it is setting pointer events to none, so even if you're passing the onPress event it is not responding to that event.

<img width="1728" alt="Screenshot 2023-10-17 at 4 06 53 PM" src="https://github.com/project44/manifest/assets/147403156/4de9f49f-2a05-4c5b-83c5-dd48756d67eb">

<img width="1728" alt="Screenshot 2023-10-17 at 4 06 38 PM" src="https://github.com/project44/manifest/assets/147403156/fb44605f-a7af-47ab-b9d6-017a6f24b314">


So if we need this functionality we need to make changes to this css, but before making any changes would like to get more context about why it was added in first place, Do you know anyone who can help with this or can design confirm what are the possible behaviours we can expect for these icons ( clickable, non clickable )

CC: @aamir-p44
