### ISSUE TITLE
[Bug]: Tooltip no longer automatically appears on truncated text

### ISSUE THREAD

**Issue by partlysean44** [project44/manifest#445]
### Description

This was reported to me by Peter Zhao.

At one time, if there was text in Movement being truncated (e.g. automatically applying the ellipsis […] to text overflows), the full text could be read in a tooltip without further setup. It appears the tooltip no longer supports that.

For example, the shipment ID visible in this screenshot should trigger a tooltip automatically.

<img width="333" alt="Screenshot 2023-08-03 at 4 57 42 PM" src="https://github.com/project44/manifest/assets/139248410/b13456e3-b1c2-4400-80af-5e366f491480">

### Link to reproduction

N/A

### Steps to reproduce

* Log into Movement
* Visit the Visibility tab
* Scroll through the Shipments table until you find text that is being truncated
* Mouse over the text—it should show a tooltip with the full text, but nothing happens.

### Code of Conduct

- [X] I agree to the [Code of Conduct](https://github.com/project44/manifest/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] I have reviewed the [current issues](https://github.com/project44/manifest/issues) for duplicate tickets.

**Comment by vivek-p44** [comment]
@p44dyoachim @aamir-p44 @vitaliy-p44  This issue is happening irrespective of whether it is truncated or untruncated text as there's `pointer-events : none` css property is added on `CellTagged` component on MWA side, which will block the pointer events on that div and children's below that. I believe this is done for escaping https://github.com/project44/manifest/issues/444 issue. 



<img width="706" alt="Screenshot 2023-10-31 at 12 35 14 PM" src="https://github.com/project44/manifest/assets/147403156/08a43f7b-a443-47b2-a7a0-ead6d3ab2697">

**Comment by vitaliy-p44** [comment]
looks like it already fixed. please close if you can confirm it.

<img width="334" alt="image" src="https://github.com/project44/manifest/assets/109169910/44feb7ab-65af-44e8-9595-74ce96ffacef">
